[package]
name = "nimiq-network-mock"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Mock network implementation for testing purposes"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
parking_lot = "0.11"
thiserror = "1.0"
tokio = { version = "1.9", features = [ "macros", "rt", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1"

beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-utils = { path = "../utils", features = ["crc"] }

[dev-dependencies]
env_logger = "0.8"
