[package]
name = "nimiq-network-libp2p"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq network implementation based on libp2p"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
futures = "0.3"
ip_network = "0.3"
libp2p = { version = "0.36", features = ["dns-tokio"] }
log = "0.4"
parking_lot = "0.9"
rand = "0.7.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
bytes = "0.5"
pin-project = "1.0"
bitflags = "1.2"
thiserror = "1.0"
hex = "0.4"
wasm-timer = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }
async-std = "1.7" # Used in some places, but can we not depend on a runtime?
dashmap = "4.0"
tokio-util = { version = "0.3", features = ["codec"] }
derive_more = "0.99"
crc = "1.8"
async-stream = "0.3"
tracing = "0.1"
tracing-futures = "0.1"
tracing-log = "0.1"
tracing-attributes = "0.1"

beserial = { path = "../beserial", features = ["libp2p"] }
beserial_derive = { path = "../beserial/beserial_derive" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-keys = { path = "../keys" }
nimiq-peer-address = { path = "../peer-address" }
nimiq-macros = { path = "../macros" }
nimiq-hash = { path = "../hash" }
nimiq-utils = { path = "../utils", features = ["tagged-signing", "serde-derive", "libp2p", "time"] }

[dev-dependencies]
tracing-subscriber = "0.2"

[features]
default = ["peer-contact-book-persistence"]
peer-contact-book-persistence = ["serde"]
memory-transport = []